'use strict';
/* Generated by the Flight transpiler */
let y = 2;
function something(x)
{
y = 6;
return x + 1;

}
function x(z)
{
return z + 1;

}
const v = Object.freeze([12, 16, 20]);
console.log(x(5));
console.log("hi");
