'use strict';
/* Generated by the Flight transpiler */
const toby = Object.freeze({
graantjes: 50,
gewicht: 20,
test: Object.freeze({
getal: 20
})
});
toby.test.getal = 50;
console.log(toby.graantjes);
console.log(toby.gewicht);
