'use strict';
/* Generated by the Flight transpiler */
function _fib(n, a, b) {
if (n == 0) {
return b;
}
 else {
return _fib(n - 1, a + b, a);
}

}

function fib(n) {
return _fib(n, 1, 0);

}

function toby(n) {
return n + 1;

}

const x = 5 + 8;
let y = 8;
const immutableObject = Object.freeze({
hi: Object.freeze({
boy: "kek"
}),
world: "yo",
kek: toby
});
let mutableObject = {
hi: {
boy: "kek"
},
world: {
shoeSize: 5
},
kek: toby
};
Object.defineProperty(mutableObject, 'world', { configurable: false, writable: false });
Object.defineProperty(mutableObject, 'shoeSize', { configurable: false, writable: false });
mutableObject.world.shoeSize = 88;
console.log(mutableObject.world);
console.log(immutableObject.kek(8));
console.log(x);
console.log(fib(1000));
console.log(toby(8));
